### ISSUE TITLE
Changes that you need to make to build a debug configuration

### ISSUE THREAD

**Issue by DiabloRusso** [mapbox/windows-builds#108]
Hi!
At the [request of Wilhelm Berg](https://github.com/mapbox/mapnik-vector-tile/issues/231#issuecomment-278675050) in this issue I will share your results on the build of mapnik debug configuration. 

I create [Pull Request](https://github.com/mapbox/windows-builds/pull/107).
To build zlib, I changed [\windows-builds\packages\zlib\contrib\vstudio\vc11\zlibvc.vcxproj](http://www.filedropper.com/zlibvc)

Later I will inform that I have changed in the project for build Mapnik.

Thanx!

**Comment by DiabloRusso** [comment]
boost 1.62, branch v3.0.x
Today my result of build.
Edit boost/spirit/home/support/attributes.hpp line 1036 as [there](https://github.com/mapnik/mapnik/issues/3573#issuecomment-270112520).
Get error:
```
 2>expression_node.obj : error LNK2019: unresolved external symbol "public:
    class std::vector<int,class std::allocator<int> > __cdecl boost::re_det
   ail_106200::icu_regex_traits_implementation::do_transform(int const *,in
   t const *,class icu_56::Collator const *)const " (?do_transform@icu_rege
   x_traits_implementation@re_detail_106200@boost@@QEBA?AV?$vector@HV?$allo
   cator@H@std@@@std@@PEBH0PEBVCollator@icu_56@@@Z) referenced in function
   "public: class std::vector<int,class std::allocator<int> > __cdecl boost
   ::re_detail_106200::icu_regex_traits_implementation::transform(int const
    *,int const *)const " (?transform@icu_regex_traits_implementation@re_de
   tail_106200@boost@@QEBA?AV?$vector@HV?$allocator@H@std@@@std@@PEBH0@Z) [
   D:\GitHub\MapnikBuilds\windows-builds\packages\mapnik-v3.0.x\mapnik-gyp\
   build\mapnik.vcxproj]
 2>expression_node.obj : error LNK2019: unresolved external symbol "public:
    bool __cdecl boost::icu_regex_traits::isctype(int,unsigned __int64)cons
   t " (?isctype@icu_regex_traits@boost@@QEBA_NH_K@Z) referenced in functio
   n "class boost::u16_to_u32_iterator<wchar_t const *,int> __cdecl boost::
   re_detail_106200::re_is_set_member<class boost::u16_to_u32_iterator<wcha
   r_t const *,int>,int,class boost::icu_regex_traits,unsigned __int64>(cla
   ss boost::u16_to_u32_iterator<wchar_t const *,int>,class boost::u16_to_u
   32_iterator<wchar_t const *,int>,struct boost::re_detail_106200::re_set_
   long<unsigned __int64> const *,struct boost::re_detail_106200::regex_dat
   a<int,class boost::icu_regex_traits> const &,bool)" (??$re_is_set_member
   @V?$u16_to_u32_iterator@PEB_WH@boost@@HVicu_regex_traits@2@_K@re_detail_
   106200@boost@@YA?AV?$u16_to_u32_iterator@PEB_WH@1@V21@0PEBU?$re_set_long
   @_K@01@AEBU?$regex_data@HVicu_regex_traits@boost@@@01@_N@Z) [D:\GitHub\M
   apnikBuilds\windows-builds\packages\mapnik-v3.0.x\mapnik-gyp\build\mapni
   k.vcxproj]
 2>expression_node.obj : error LNK2019: unresolved external symbol "private
   : class boost::basic_regex<int,class boost::icu_regex_traits> & __cdecl
   boost::basic_regex<int,class boost::icu_regex_traits>::do_assign(int con
   st *,int const *,unsigned int)" (?do_assign@?$basic_regex@HVicu_regex_tr
   aits@boost@@@boost@@AEAAAEAV12@PEBH0I@Z) referenced in function "public:
    class boost::basic_regex<int,class boost::icu_regex_traits> & __cdecl b
   oost::basic_regex<int,class boost::icu_regex_traits>::assign(int const *
   ,int const *,unsigned int)" (?assign@?$basic_regex@HVicu_regex_traits@bo
   ost@@@boost@@QEAAAEAV12@PEBH0I@Z) [D:\GitHub\MapnikBuilds\windows-builds
   \packages\mapnik-v3.0.x\mapnik-gyp\build\mapnik.vcxproj]
 2>lib\mapnik.dll : fatal error LNK1120: 3 unresolved externals [D:\GitHub\
   MapnikBuilds\windows-builds\packages\mapnik-v3.0.x\mapnik-gyp\build\mapn
   ik.vcxproj]
```
I saw [it](https://github.com/mapbox/windows-builds/issues/88), but not yet understand how to solve.

**Comment by BergWerkGIS** [comment]
@DiabloRusso I merged your PRs (https://github.com/mapbox/windows-builds/pull/107 and https://github.com/mapnik/mapnik-gyp/pull/30) into `Debug` branches of the respective respositories (https://github.com/mapbox/windows-builds/tree/Debug, https://github.com/mapnik/mapnik-gyp/tree/Debug).

I also added patches for the boost `std::swap` issues so **4.** shouldn't be neceassary anymore.

Trying to replicate:
* `git clone -b Debug https://github.com/mapbox/windows-builds.git windows-builds-DEBUG`
* `cd windows-builds-DEBUG`
* `settings  "FASTBUILD=0" "BUILD_TYPE=Debug" "MAPNIKBRANCH=v3.0.x" "MAPNIKGYPBRANCH=Debug"`
* `scriptcs scripts\build.csx -- upto=mapnik` <- use this instead of `scripts\build.bat` to get log files in directory `build-logs`
* **3.** as there is no patch yet for `zlib`
* `scriptcs scripts\build.csx -- upto=mapnik`

Unfortunately I still get this error (`LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs;`) <- conflict `Release`/`Debug`.

Any ideas what I may have missed?

----

Full error:

<pre>
         Debug\obj\mapnik\..\..\src\/unicode.obj
         Debug\obj\mapnik\..\..\src\/value.obj
         Debug\obj\mapnik\..\..\src\/vertex_adapters.obj
         Debug\obj\mapnik\..\..\src\/vertex_cache.obj
         Debug\obj\mapnik\..\..\src\/warp.obj
         Debug\obj\mapnik\..\..\src\/webp_reader.obj
         Debug\obj\mapnik\..\..\src\/well_known_srs.obj
         Debug\obj\mapnik\..\..\src\/wkb.obj
         Debug\obj\mapnik\..\..\src\/xml_tree.obj
            Creating library c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\Debug\mapnik.lib and object c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\Debug\mapnik.exp
         Linker: LibDef Total time = 0.14959s PB: 1578319872 [c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\lib\mapnik.dll] 
     2><b>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs;</b> use /NODEFAULTLIB:library [c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\mapnik.vcxproj]
     2>expression_node.obj : error LNK2019: unresolved external symbol "public: class std::vector<int,class std::allocator<int> > __cdecl boost::re_detail_106200::icu_regex_traits_implementation::do_transform(int const *,int const *,class icu_56::Collator const *)const " (?do_transform@icu_regex_traits_implementation@re_detail_106200@boost@@QEBA?AV?$vector@HV?$allocator@H@std@@@std@@PEBH0PEBVCollator@icu_56@@@Z) referenced in function "public: class std::vector<int,class std::allocator<int> > __cdecl boost::re_detail_106200::icu_regex_traits_implementation::transform(int const *,int const *)const " (?transform@icu_regex_traits_implementation@re_detail_106200@boost@@QEBA?AV?$vector@HV?$allocator@H@std@@@std@@PEBH0@Z) [c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\mapnik.vcxproj]
     2>expression_node.obj : error LNK2019: unresolved external symbol "public: bool __cdecl boost::icu_regex_traits::isctype(int,unsigned __int64)const " (?isctype@icu_regex_traits@boost@@QEBA_NH_K@Z) referenced in function "class boost::u16_to_u32_iterator<wchar_t const *,int> __cdecl boost::re_detail_106200::re_is_set_member<class boost::u16_to_u32_iterator<wchar_t const *,int>,int,class boost::icu_regex_traits,unsigned __int64>(class boost::u16_to_u32_iterator<wchar_t const *,int>,class boost::u16_to_u32_iterator<wchar_t const *,int>,struct boost::re_detail_106200::re_set_long<unsigned __int64> const *,struct boost::re_detail_106200::regex_data<int,class boost::icu_regex_traits> const &,bool)" (??$re_is_set_member@V?$u16_to_u32_iterator@PEB_WH@boost@@HVicu_regex_traits@2@_K@re_detail_106200@boost@@YA?AV?$u16_to_u32_iterator@PEB_WH@1@V21@0PEBU?$re_set_long@_K@01@AEBU?$regex_data@HVicu_regex_traits@boost@@@01@_N@Z) [c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\mapnik.vcxproj]
     2>expression_node.obj : error LNK2019: unresolved external symbol "private: class boost::basic_regex<int,class boost::icu_regex_traits> & __cdecl boost::basic_regex<int,class boost::icu_regex_traits>::do_assign(int const *,int const *,unsigned int)" (?do_assign@?$basic_regex@HVicu_regex_traits@boost@@@boost@@AEAAAEAV12@PEBH0I@Z) referenced in function "public: class boost::basic_regex<int,class boost::icu_regex_traits> & __cdecl boost::basic_regex<int,class boost::icu_regex_traits>::assign(int const *,int const *,unsigned int)" (?assign@?$basic_regex@HVicu_regex_traits@boost@@@boost@@QEAAAEAV12@PEBH0I@Z) [c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\mapnik.vcxproj]
     2>lib\mapnik.dll : fatal error LNK1120: 3 unresolved externals [c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\mapnik.vcxproj]
         Linker:   Wait PDB close Total time = 0.00486s PB: 1585659904 [c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\lib\mapnik.dll] 
         Linker:   Wait type merge Total time = 0.17471s PB: 1584013312 [c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\lib\mapnik.dll] 
         Linker: Final Total time = 14.40621s < 65469356643 - 65613418791 > PB: 214474752 [c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\lib\mapnik.dll] 
     2>Done Building Project "c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\mapnik.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "c:\mb\windows-builds-DEBUG\packages\mapnik-v3.0.x\mapnik-gyp\build\mapnik.sln" (mapnik;mapnik-json;mapnik-wkt;mapnik-render;shapeindex;mapnik-index;csv;gdal;geojson;ogr;pgraster;postgis;raster;shape;sqlite;topojson;test;test_visual_run;test_rendering;test_expression_parse;test_face_ptr_creation;test_font_registration;test_offset_converter;test_proj_transform1;test_quad_tree target(s)) -- FAILED.

Build FAILED.
</pre>

**Comment by BergWerkGIS** [comment]
Tried to build just mapnik a second time (`scriptcs scripts\build.csx -- build=mapnik`) and now get:

![image](https://cloud.githubusercontent.com/assets/4549888/22882389/c9ba9024-f1e2-11e6-8086-f997f5d1d429.png)

**Comment by DiabloRusso** [comment]
`Unfortunately I still get this error (LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs;) <- conflict Release/Debug.`
@BergWerkGIS I also get this warning, but still I did not attach importance to it.
I saw that gdal201.dll depends on MSVCP140.dll and VCRUNTIME140.dll. It is necessary to check the build type of gdal!

**Comment by BergWerkGIS** [comment]
@DiabloRusso gdal is still `Release`: https://github.com/mapbox/mapnik-vector-tile/issues/231#issuecomment-278712938

**Comment by DiabloRusso** [comment]
@BergWerkGIS To build debug libtiff manually changed \packages\libtiff\nmake.opt and replace line 117 /MD to /MDd

**Comment by BergWerkGIS** [comment]
@DiabloRusso that's great.

Would you be open to contribute those fixes to the `Debug` branches to get a fully automated process with no manual actions that just works by specifying either `"BUILD_TYPE=Debug"` or `"BUILD_TYPE=Release"` when calling `settings.bat`?

Thinking about
* zlib
* libtiff
* gdal

Like the other patches that live here: https://github.com/mapbox/windows-builds/tree/Debug/patches

**Comment by DiabloRusso** [comment]
@BergWerkGIS Ok, I'll try to do it! It will take some time... I am newbie in github))))

**Comment by DiabloRusso** [comment]
@BergWerkGIS I create [PR](https://github.com/mapbox/windows-builds/pull/109)
But there was remain one problem, see my first post issue **5.**, how to fix `has_icu = false`? If not for that, automatic building was completed successfully(((((

**Comment by BergWerkGIS** [comment]
Thanks @DiabloRusso - we'll find a way to make **5.** (icu) work.

I've done several full clean builds now, but I'm still getting the errors [posted above](https://github.com/mapbox/windows-builds/issues/108#issuecomment-279366067) when running tests.
Do you see those too?

**Comment by DiabloRusso** [comment]
@BergWerkGIS I had not set the goal to correct the tests, but I'll see)))
